language: node_js
node_js:
- node
install:
- npm install
script:
- npm test
deploy:
  provider: npm
  email: andreas@softbrix.se
  api_key:
    secure: mYKFklG71Y18TYESn5byKOyrMAaxkNqhonK5NM1YbqK/0y0M2wjODVKXIwur9DOLQP0ame9iDrlH7Utt18VlHdKf6tEwfiTNAa2RmOtatV3HfoPfriZnE3ycVRswb5n0XMJlBPHrbhZ5/ubhFXZGAID1FQ4LyaSUgQfx8hkCCNeGFaISku3WzIevpsGqSDj7mWn+EumA/etHIdUPtxVdbr4wdTKPIIO2i6mCKHPYPS0CcMh8FfjyzjGQXy+ncEIQ5lvrAu7nSBBAWETxB6geqa18HmqXw2AK5yiWHGXqXt9MtcCU0/mbpy5oF1HhYKBr4KtY3RcdHraWmwnwj6dF8iEe7pbbJsNOJ0Stq2Hjfn0zLjpwaWAPI7hvNlbHMWr6DfewwTo0WLjYAi6IlkCCOaVPmkpccdT8ntFKQyMjxqDDLRaN9ewJrS0We7vLJ/5fn6UbBKVXk4wvlhZsxW4dxw76ElVxY9uujLj7w+oM8dHMGJKuUPIjSCTt8M53eKaJxNPll4whF3PYIeVNY3Yf97qbATFxbHQFNXvlAvBRYyQo1OUO8JekqJwtQwMuAgCieMzSd0Q86jyww6gYFALsjjaYv5hJl264IrkC9vb+zcmrT2iWKBdtKVERjczpqXMYTB1y5PgwuhCtn8zzP+iRIjdcILGgyY+9Jb+Hs71bjDw=
  on:
    tags: true
    repo: softbrix/stureby_index
